/*
 *  Java
 */
package com.example.microej;

import com.example.microej.bench.StartupProbe;
import ej.microui.MicroUI;

/**
 * Generated by the application template.
 * <p>
 * Please keep it in sync with the property 'applicationEntryPoint' defined in build.gradle.kts.
 */
public class Main {

	static {
		// As early as we can in application code.
		try {
			StartupProbe.markAppClassLoaded();
		} catch (Throwable ignored) {
			// ignore
		}
	}

	public static void main(String[] args) {
		try {
			System.out.println("[App] main() start");
		} catch (Throwable ignored) {
			// ignore
		}
		MicroUI.start();
		DemoApp.showMenu();
		try {
			System.out.println("[App] UI requested (menu)");
		} catch (Throwable ignored) {
			// ignore
		}
	}
}