/*
 *  Java
 */
package com.example.microej;


import ej.microui.MicroUI;

/**
 * Generated by the application template.
 * <p>
 * Please keep it in sync with the property 'applicationEntryPoint' defined in build.gradle.kts.
 */
public class Main {

    public static void main(String[] args) {
        MicroUI.start();
        DemoApp.showMenu();
    }
}